### Backend APIs
### Just some helpful, test calls using JetBrains .http magic


# Individual launch api
# https://api.spacexdata.com/v5/launches/:id
# https://api.spacexdata.com/v5/launches/62dd70d5202306255024d139
# Local
GET http://localhost:4200/api/launches/id/5e9d0d95eda69974db09d1ed
###
GET http://localhost:4200/api/launches/id/5e9d0d95eda69974db09d1ed

### External launches
GET https://api.spacexdata.com/v5/launches/62dd70d5202306255024d139

### Empty result
GET https://api.spacexdata.com/v4/launches/5e9d0d95eda69955f709d1eb
#GET https://api.spacexdata.com/v5/launches/5e9d0d95eda69974db09d1ed
#http://localhost:4200/api/launches/id/5e9d0d95eda69974db09d1ed

###
GET http://localhost:4200/api/rockets/all:;harmful code


### all rockets
GET localhost:8080/api/rockets/all


### all launces
GET localhost:8080/api/launches/all


### Data source apis
### Provided via: https://github.com/r-spacex/SpaceX-API
GET https://api.spacexdata.com/v5/launches/latest


### Rockets
GET https://api.spacexdata.com/v4/rockets

### Launches
GET https://api.spacexdata.com/v4/launches
